spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_intcomex?useSSL=false
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # o validate
    show-sql: false
